name: CI
on:
  push:
    branches:
    - master

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo cargo build
    - run: sudo cargo run
