name: CI
on:
  push:
    branches:
    - master

jobs:
  rust:
    name: Rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: perf stat ls || true
    - run: cargo build
    - run: sudo ./target/debug/perftest || true
